#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i 's/location /redirect_me/location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }/' /etc/nginx/sites-available/default
