#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
