#!/usr/bin/env bash
# Install nginx web server

sudo apt update
sudo apt install -y nginx
sudo mkdir /etc/nginx/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /not_found_404.html;
    location = /not_found_40.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /etc/nginx/html/not_found_404.html
sudo service nginx restart
