#!/usr/bin/env bash
# web 2

sudo apt update
sudo apt install -y nginx
sudo mkdir /etc/nginx/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /not_found_404.html;\n
        location = /not_found_404.html{\n
                root /etc/nginx/html;\n
                internal;\n
        }/' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /etc/nginx/html/not_found_404.html
sudo service nginx restart
