#!/usr/bin/env bash
# debugging
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=on//' /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=on//' /etc/nginx/sites-available/default
sudo service nginx restart
