#!/usr/bin/env bash
# debugging
echo -e "server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server ipv6only=on;\n\n\troot /usr/share/nginx/html;\n\tindex index.html index.htm;\n\n\tserver_name localhost;\n\n}" > /etc/nginx/sites-enabled/default
sudo service nginx restart
