#!/usr/bin/env bash
#fizzbuzz
s=1
while [ $s -le 100 ]
do
	if [ $((s % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((s % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((s % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$s"
	fi
	s=$((s + 1))
done
