#!/usr/bin/env bash
#script to display best school 10 times using while
s=1
while [ $s -le 20 ]
do
	echo "$s"
	case $s in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	esac
	s=$((s + 1))
done
