#!/usr/bin/env bash
#script to display best school 10 times using while
s=1
while [ $s -le 20 ]
do
	echo "$s"
	if [ $s = 4 ]
	then
		echo "bad luck from China"
	fi
	if [ $s = 9 ]
	then
		echo "bad luck from Japan"
	fi
	if [ $s = 17 ]
	then
		echo "bad luck from Italy"
	fi
	s=$((s + 1))
done
